"""oauth_tokens keep history when client deleted

Revision ID: 1ee09c99d84d
Revises: 8813dec38e2b
Create Date: 2026-09-01 03:29:46.975556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from db.database import NAMING_CONVENTION


# revision identifiers, used by Alembic.
revision: str = '1ee09c99d84d'
down_revision: Union[str, Sequence[str], None] = '8813dec38e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_tokens', schema=None, naming_convention=NAMING_CONVENTION) as batch_op:
        batch_op.add_column(sa.Column('client_name_snapshot', sa.String(length=128), nullable=True))
        batch_op.alter_column('client_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_constraint('fk_oauth_tokens_client_id_oauth_clients', type_='foreignkey')
        batch_op.create_foreign_key('fk_oauth_tokens_client_id_oauth_clients', 'oauth_clients', ['client_id'], ['client_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_tokens', schema=None, naming_convention=NAMING_CONVENTION) as batch_op:
        batch_op.drop_constraint('fk_oauth_tokens_client_id_oauth_clients', type_='foreignkey')
        batch_op.create_foreign_key('fk_oauth_tokens_client_id_oauth_clients', 'oauth_clients', ['client_id'], ['client_id'], ondelete='CASCADE')
        batch_op.alter_column('client_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('client_name_snapshot')

    # ### end Alembic commands ###
