"""init

Revision ID: 8813dec38e2b
Revises: 
Create Date: 2026-08-31 08:26:02.779058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8813dec38e2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('auth_provider', sa.String(length=16), nullable=False),
    sa.Column('provider_sub', sa.String(length=128), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_users_provider_sub'), ['provider_sub'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=True),
    sa.Column('actor_name', sa.String(length=128), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('request_path', sa.String(length=256), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('status_code', sa.String(length=10), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_status'), ['status'], unique=False)

    op.create_table('oauth_scopes',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('oauth_signing_keys',
    sa.Column('kid', sa.String(length=64), nullable=False),
    sa.Column('alg', sa.String(length=16), nullable=False),
    sa.Column('public_jwk', sa.Text(), nullable=False),
    sa.Column('private_pem_enc', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('kid')
    )
    with op.batch_alter_table('oauth_signing_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_signing_keys_is_active'), ['is_active'], unique=False)

    op.create_table('services',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('host', sa.String(length=128), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('protocol', sa.String(length=16), nullable=True),
    sa.Column('mcp_path', sa.String(length=128), nullable=True),
    sa.Column('auth_token_encrypted', sa.String(length=1024), nullable=True),
    sa.Column('requires_auth', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('oauth_audience', sa.String(length=256), nullable=True),
    sa.Column('oauth_scopes', sa.String(length=512), nullable=True),
    sa.Column('health_status', sa.String(length=32), nullable=True),
    sa.Column('health_last_checked', sa.DateTime(), nullable=True),
    sa.Column('health_response_time_ms', sa.Float(), nullable=True),
    sa.Column('health_error_message', sa.String(length=512), nullable=True),
    sa.Column('health_fail_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_oauth_audience'), ['oauth_audience'], unique=False)

    op.create_table('managed_mcp_processes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('catalog_id', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('docker_image', sa.String(length=256), nullable=False),
    sa.Column('image_args', sa.String(length=512), nullable=True),
    sa.Column('image_command', sa.Text(), nullable=True),
    sa.Column('env_vars_encrypted', sa.Text(), nullable=True),
    sa.Column('bridge_type', sa.String(length=32), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('auto_port', sa.Boolean(), nullable=False),
    sa.Column('desired_state', sa.String(length=16), nullable=False),
    sa.Column('actual_state', sa.String(length=16), nullable=False),
    sa.Column('container_id', sa.String(length=128), nullable=True),
    sa.Column('bridge_container_id', sa.String(length=128), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_log_lines', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['admin_users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('managed_mcp_processes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_managed_mcp_processes_catalog_id'), ['catalog_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_managed_mcp_processes_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_managed_mcp_processes_service_id'), ['service_id'], unique=False)

    op.create_table('mcp_tools',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('input_schema', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mcp_tools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mcp_tools_service_id'), ['service_id'], unique=False)

    op.create_table('oauth_clients',
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('client_secret_hash', sa.String(length=128), nullable=True),
    sa.Column('client_name', sa.String(length=128), nullable=False),
    sa.Column('client_uri', sa.String(length=512), nullable=True),
    sa.Column('logo_uri', sa.String(length=512), nullable=True),
    sa.Column('software_id', sa.String(length=128), nullable=True),
    sa.Column('redirect_uris', sa.Text(), nullable=False),
    sa.Column('grant_types', sa.Text(), nullable=False),
    sa.Column('response_types', sa.Text(), nullable=False),
    sa.Column('scope', sa.String(length=512), nullable=True),
    sa.Column('token_endpoint_auth_method', sa.String(length=32), nullable=False),
    sa.Column('created_via', sa.String(length=16), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('client_id')
    )
    with op.batch_alter_table('oauth_clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_clients_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_clients_is_approved'), ['is_approved'], unique=False)

    op.create_table('token_usage',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=True),
    sa.Column('event', sa.String(length=16), nullable=False),
    sa.Column('grant_type', sa.String(length=32), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('sub', sa.String(length=128), nullable=True),
    sa.Column('audience', sa.String(length=256), nullable=True),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('token_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_token_usage_audience'), ['audience'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_usage_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_usage_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_usage_jti'), ['jti'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_usage_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_token_usage_used_at'), ['used_at'], unique=False)

    op.create_table('user_mcp_definitions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('command', sa.String(length=32), nullable=False),
    sa.Column('args_json', sa.Text(), nullable=True),
    sa.Column('container_port', sa.Integer(), nullable=False),
    sa.Column('env_schema_json', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_mcp_definitions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_mcp_definitions_created_by_id'), ['created_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_mcp_definitions_name'), ['name'], unique=True)

    op.create_table('oauth_authorization_codes',
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('redirect_uri', sa.String(length=512), nullable=False),
    sa.Column('scope', sa.String(length=512), nullable=True),
    sa.Column('resource', sa.String(length=256), nullable=True),
    sa.Column('code_challenge', sa.String(length=128), nullable=False),
    sa.Column('code_challenge_method', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code_hash')
    )
    with op.batch_alter_table('oauth_authorization_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_authorization_codes_client_id'), ['client_id'], unique=False)

    op.create_table('oauth_authorization_requests',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('redirect_uri', sa.String(length=512), nullable=False),
    sa.Column('scope', sa.String(length=512), nullable=True),
    sa.Column('resource', sa.String(length=256), nullable=True),
    sa.Column('state', sa.String(length=512), nullable=True),
    sa.Column('code_challenge', sa.String(length=128), nullable=False),
    sa.Column('code_challenge_method', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('oauth_authorization_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_authorization_requests_client_id'), ['client_id'], unique=False)

    op.create_table('oauth_consents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('audience', sa.String(length=256), nullable=True),
    sa.Column('scope', sa.String(length=512), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'client_id', 'audience', name='uq_oauth_consent')
    )
    with op.batch_alter_table('oauth_consents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_consents_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_consents_user_id'), ['user_id'], unique=False)

    op.create_table('oauth_tokens',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('sub', sa.String(length=128), nullable=False),
    sa.Column('audience', sa.String(length=256), nullable=True),
    sa.Column('service_id', sa.Uuid(), nullable=True),
    sa.Column('scope', sa.String(length=512), nullable=True),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('parent_jti', sa.String(length=64), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoke_reason', sa.String(length=64), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('jti')
    )
    with op.batch_alter_table('oauth_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_tokens_audience'), ['audience'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_tokens_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_tokens_issued_at'), ['issued_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_tokens_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_tokens_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_tokens_service_id'), ['service_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_oauth_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('oauth_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_tokens_service_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_tokens_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_oauth_tokens_kind'))
        batch_op.drop_index(batch_op.f('ix_oauth_tokens_issued_at'))
        batch_op.drop_index(batch_op.f('ix_oauth_tokens_expires_at'))
        batch_op.drop_index(batch_op.f('ix_oauth_tokens_client_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_tokens_audience'))

    op.drop_table('oauth_tokens')
    with op.batch_alter_table('oauth_consents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_consents_user_id'))
        batch_op.drop_index(batch_op.f('ix_oauth_consents_client_id'))

    op.drop_table('oauth_consents')
    with op.batch_alter_table('oauth_authorization_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_authorization_requests_client_id'))

    op.drop_table('oauth_authorization_requests')
    with op.batch_alter_table('oauth_authorization_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_authorization_codes_client_id'))

    op.drop_table('oauth_authorization_codes')
    with op.batch_alter_table('user_mcp_definitions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_mcp_definitions_name'))
        batch_op.drop_index(batch_op.f('ix_user_mcp_definitions_created_by_id'))

    op.drop_table('user_mcp_definitions')
    with op.batch_alter_table('token_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_token_usage_used_at'))
        batch_op.drop_index(batch_op.f('ix_token_usage_service_id'))
        batch_op.drop_index(batch_op.f('ix_token_usage_jti'))
        batch_op.drop_index(batch_op.f('ix_token_usage_event'))
        batch_op.drop_index(batch_op.f('ix_token_usage_client_id'))
        batch_op.drop_index(batch_op.f('ix_token_usage_audience'))

    op.drop_table('token_usage')
    with op.batch_alter_table('oauth_clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_clients_is_approved'))
        batch_op.drop_index(batch_op.f('ix_oauth_clients_is_active'))

    op.drop_table('oauth_clients')
    with op.batch_alter_table('mcp_tools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mcp_tools_service_id'))

    op.drop_table('mcp_tools')
    with op.batch_alter_table('managed_mcp_processes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_managed_mcp_processes_service_id'))
        batch_op.drop_index(batch_op.f('ix_managed_mcp_processes_name'))
        batch_op.drop_index(batch_op.f('ix_managed_mcp_processes_catalog_id'))

    op.drop_table('managed_mcp_processes')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_oauth_audience'))
        batch_op.drop_index(batch_op.f('ix_services_name'))

    op.drop_table('services')
    with op.batch_alter_table('oauth_signing_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_signing_keys_is_active'))

    op.drop_table('oauth_signing_keys')
    op.drop_table('oauth_scopes')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_status'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_users_provider_sub'))
        batch_op.drop_index(batch_op.f('ix_admin_users_email'))

    op.drop_table('admin_users')
    # ### end Alembic commands ###
